### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by uzairhussain777** [cytomining/DeepProfiler#190]
when i am trying this command,
**python deepprofiler --root=/home/ubuntu/project setup**
**this gives error** 
Traceback (most recent call last):
![Screenshot from 2019-11-20 09-26-37](https://user-images.githubusercontent.com/25324889/69210970-59e22880-0b7e-11ea-9633-2291f39d079c.png)
![Screenshot from 2019-11-20 09-29-15](https://user-images.githubusercontent.com/25324889/69210974-5e0e4600-0b7e-11ea-8789-6305cf80cd12.png)

  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/uzairhussain/Documents/DeepProfiler-master/deepprofiler/__main__.py", line 6, in <module>
    import deepprofiler.dataset.compression
  File "/home/uzairhussain/Documents/DeepProfiler-master/deepprofiler/dataset/compression.py", line 37
    print("Percentiles for the", side, " >> ", end="")

**Comment by Arkkienkeli** [comment]
@uzairhussain777 
Hi, you are using python version 2.7; in order to make it work, you should use python version 3.
