### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by dlogan** [cytomining/DeepProfiler#225]
I am installing DeepProfiler and running this for the first time, but I get a ModuleNotFoundError:
```
$ python3 ./deepprofiler
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./deepprofiler/__main__.py", line 7, in <module>
    import deepprofiler.dataset.compression
ModuleNotFoundError: No module named 'deepprofiler'
```

Maybe a rookie mistake, but I solved this on Linux with:
```
export PYTHONPATH=.
```
Consider adding a note to the wiki if this is useful?

**Comment by jccaicedo** [comment]
Thanks for reporting!
If you are in the DeepProfiler directory, I think you don't need to use `./` before `deepprofiler`. Can you try if this works for you? (just using `python3 deepprofiler`).

**Comment by dlogan** [comment]
Thanks for the reply! But nope:
```
$ python3 deepprofiler
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "deepprofiler/__main__.py", line 7, in <module>
    import deepprofiler.dataset.compression
ModuleNotFoundError: No module named 'deepprofiler'
```

Though when I add back in 
```
$ export PYTHONPATH=.
```
 then it returns the expected output, i.e.:
```
$ python3 deepprofiler
Using TensorFlow backend.
2020-05-01 21:31:43.487515: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-01 21:31:43.492856: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
Usage: deepprofiler [OPTIONS] COMMAND [ARGS]...

Options:
  --root PATH         Root directory for DeepProfiler experiment
  --config TEXT       Path to existing config file
  --cores INTEGER     Number of CPU cores for parallel processing (all=0)
  --gpu TEXT          GPU device id
  --exp TEXT          Name of experiment
  --cometml_key TEXT  Path to file with comet.ml API key
  --help              Show this message and exit.

Commands:
  download-bbbc021
  prepare
  profile
  setup
  split
  train
```

I'm running Ubuntu 18.04.4 LTS in case that matters.

**Comment by dlogan** [comment]
Well, now that I'm using a venv, this works ok.  I must've had a conflict with my environment, sorry.  

I still get a number of warnings, but they appear harmless (for now):
```
(venv) logand05@cortex:~/github/DeepProfiler$ python3 deepprofiler
Using TensorFlow backend.
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/logand05/github/DeepProfiler/venv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Usage: deepprofiler [OPTIONS] COMMAND [ARGS]...

Options:
  --root PATH         Root directory for DeepProfiler experiment
  --config TEXT       Path to existing config file
  --cores INTEGER     Number of CPU cores for parallel processing (all=0)
  --gpu TEXT          GPU device id
  --exp TEXT          Name of experiment
  --cometml_key TEXT  Path to file with comet.ml API key
  --help              Show this message and exit.

Commands:
  download-bbbc021
  prepare
  profile
  setup
  split
  train
```
Closing.
