### ISSUE TITLE
Comet_ml 

### ISSUE THREAD

**Issue by dlogan** [cytomining/DeepProfiler#226]
I got this trying to install
```
 $ python3 ./deepprofiler
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./deepprofiler/__main__.py", line 14, in <module>
    import deepprofiler.learning.training
  File "/home/logand05/github/DeepProfiler/deepprofiler/learning/__init__.py", line 3, in <module>
    from comet_ml import Experiment
ModuleNotFoundError: No module named 'comet_ml'
```
This was solved with a simple
```
pip3 install comet_ml
```
Consider adding this prerequisite to the Wiki https://github.com/cytomining/DeepProfiler/wiki/1.-Installing-DeepProfiler

**Comment by Arkkienkeli** [comment]
Hi @dlogan, thank you for reporting this. 
I added `comet-ml` package to `setup.py` c1c39e92b41781218b2e0c6fed52011cefb0b05e
