### ISSUE TITLE
Profiling on Resnet gives error

### ISSUE THREAD

**Issue by michaelbornholdt** [cytomining/DeepProfiler#271]
https://github.com/cytomining/DeepProfiler/blob/18921e480e72f4c519fb5afdc30fdcef09f7cde5/deepprofiler/learning/profiling.py#L43

@jccaicedo  @Arkkienkeli says this line needs to change. Is this only the case for REsnet? Why does it only fail for Resnet? 

Unfortunately, I can't easily change these things in the docker so I need a branch which has all the improvements of the past weeks but does not include the augmentation. Could someone do that for me?

**Comment by michaelbornholdt** [comment]
Error: 

```
raceback (most recent call last):
  File "/DeepProfiler/deepprofiler/learning/profiling.py", line 41, in configure
    self.dpmodel.feature_model.load_weights(checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training_v1.py", line 232, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 2326, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 691, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 103 layers into a model with 132 layers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2201, in __setattr__
    super(tracking.AutoTrackable, self).__setattr__(name, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "deepprofiler/__main__.py", line 197, in <module>
    cli(obj={})
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "deepprofiler/__main__.py", line 181, in profile
    deepprofiler.learning.profiling.profile(context.obj["config"], dset)
  File "/DeepProfiler/deepprofiler/learning/profiling.py", line 105, in profile
    profile.configure()
  File "/DeepProfiler/deepprofiler/learning/profiling.py", line 44, in configure
    self.dpmodel.feature_model.layers[-1].name = "classifier"
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 2206, in __setattr__
    'different name.').format(name))
AttributeError: Can't set the attribute "name", likely because it conflicts with an existing read-only @property of the object. Please choose a differ
ent name.
```

**Comment by Arkkienkeli** [comment]
PR https://github.com/cytomining/DeepProfiler/pull/270 solves this issue.
Thank you @johnarevalo !
